### PR TITLE
Add Makefile for building and installing helper

### PR DESCRIPTION
**Pull request by cornelius**

### CODE REVIEW

**Comment by mauromorales** [comment]
@cornelius learning a bit here so let me ask something. Do we need to set the GOPATH or any other env var depending on the arch it will be built? or is this because we are doing it just on one right now?

**Comment by mauromorales** [comment]
besides my question lgtm

**Comment by cornelius** [comment]
I would assume that developers have a working setup for the architecture they are working on, so that things don't have to be set. Maybe this needs some refinement, when we use the Makefile for packaging as well. For now the purpose of the Makefile just is to make local development easier and more reproducible.

**Comment by mauromorales** [comment]
@cornelius got it :+1:

**Pull request merged**
